### Login 요청
POST http://localhost:8080/login
Content-Type: application/json

{
  "id": "user",
  "password": "1234"
}

> {%
  client.global.set("session_id",
      response.headers.valueOf("Set-Cookie").match(/SESSION=([^;]+)/)[1]);
%}

### Validate 세션 (성공 케이스)
GET http://localhost:8080/validate
Cookie: SESSION={{session_id}}

### Validate 세션 (실패 케이스 - 쿠키 없음)
GET http://localhost:8080/validate
