spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties.hibernate.format_sql: true

  # h2 ?????? ?? ??
  h2:
    console:
      enabled: true
      path: /h2-console

  # h2 ?????? ??
  datasource:
    url: jdbc:h2:mem:session-log
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # ?? ??? ??
  sql.init.mode: embedded
  jpa.defer-datasource-initialization: true

logging.level.org.hibernate:
  SQL: DEBUG
  orm:jdbc:bind: TRACE
